"""Compatibility bridge for extracted storage, auth and AI modules."""
from core import server_impl
from core.auth import clean_id, normalize_email, valid_email, hash_password, verify_password, get_accounts, get_sessions, cookie, create_session, current_user
from core.ai_manager import (get_ai_registry, account_root, ais_root, ai_root, settings_file, conversations_root, conversation_path, legacy_conversation_file, load_archived_conversation, save_archived_conversation, blank_settings, load_settings, save_settings, load_conversation, save_conversation_data, migrate_legacy_ai, ensure_first_ai, list_ais, active_ai, set_active, create_ai, delete_ai)
from core.config import (PORT, PUBLIC_HOSTNAME, PUBLIC_URL, RECENT_CONTEXT_MESSAGES, RELEVANT_MEMORY_LIMIT, PROACTIVE_MIN_MINUTES, PROACTIVE_MAX_MINUTES, MAX_AIS_PER_ACCOUNT, BASE_DIR, USERS_DIR, AUTH_FILE, SESSIONS_FILE, AIS_FILE)
from core.storage import load_json, save_json

def apply():
    module=server_impl
    for name,value in {"PORT":PORT,"PUBLIC_HOSTNAME":PUBLIC_HOSTNAME,"PUBLIC_URL":PUBLIC_URL,"RECENT_CONTEXT_MESSAGES":RECENT_CONTEXT_MESSAGES,"RELEVANT_MEMORY_LIMIT":RELEVANT_MEMORY_LIMIT,"PROACTIVE_MIN_MINUTES":PROACTIVE_MIN_MINUTES,"PROACTIVE_MAX_MINUTES":PROACTIVE_MAX_MINUTES,"MAX_AIS_PER_ACCOUNT":MAX_AIS_PER_ACCOUNT,"BASE_DIR":BASE_DIR,"USERS_DIR":USERS_DIR,"AUTH_FILE":AUTH_FILE,"SESSIONS_FILE":SESSIONS_FILE,"AIS_FILE":AIS_FILE}.items():setattr(module,name,value)
    for name,value in {"load_json":load_json,"save_json":save_json,"clean_id":clean_id,"normalize_email":normalize_email,"valid_email":valid_email,"hash_password":hash_password,"verify_password":verify_password,"get_accounts":get_accounts,"get_sessions":get_sessions,"cookie":cookie,"create_session":create_session,"current_user":current_user}.items():setattr(module,name,value)
    for name,value in {"get_ai_registry":get_ai_registry,"account_root":account_root,"ais_root":ais_root,"ai_root":ai_root,"settings_file":settings_file,"conversations_root":conversations_root,"conversation_path":conversation_path,"legacy_conversation_file":legacy_conversation_file,"load_archived_conversation":load_archived_conversation,"save_archived_conversation":save_archived_conversation,"blank_settings":blank_settings,"load_settings":load_settings,"save_settings":save_settings,"load_conversation":load_conversation,"save_conversation_data":save_conversation_data,"migrate_legacy_ai":migrate_legacy_ai,"ensure_first_ai":ensure_first_ai,"list_ais":list_ais,"active_ai":active_ai,"set_active":set_active,"create_ai":create_ai,"delete_ai":delete_ai}.items():setattr(module,name,value)
    return module
